package hangman;

public enum Words {
    WATERMELON("WATERMELON", "FRUIT"), BLACKBERRY("BLACKBERRY", "FRUIT"), PINEAPPLE("PINEAPPLE", "FRUIT"),
    RASPBERRY("RASPBERRY", "FRUIT"), BLUEBERRY("BLUEBERRY", "FRUIT"), CANTALOUPE("CANTALOUPE", "FRUIT"),
    GRAPEFRUIT("GRAPEFRUIT", "FRUIT"), ASPARAGUS("ASPARAGUS", "VEGETABLE"), ARTICHOKE("ARTICHOKE", "VEGETABLE"),
    CUCUMBER("CUCUMBER", "VEGETABLE"), EGGPLANT("EGGPLANT", "VEGETABLE"), BROCCOLI("BROCCOLI", "VEGETABLE"),
    ZUCCHINI("ZUCCHINI", "VEGETABLE"), CABBAGE("CABBAGE", "VEGETABLE"), SPINACH("SPINACH", "VEGETABLE"),
    MUSHROOM("MUSHROOM", "VEGETABLE"), LETTUCE("LETTUCE", "VEGETABLE"), POTATO("POTATO", "VEGETABLE"),
    RADISH("RADISH", "VEGETABLE"), APRICOT("APRICOT", "FRUIT"), AVOCADO("AVOCADO", "FRUIT"),
    COCONUT("COCONUT", "FRUIT"), CRANBERRY("CRANBERRY", "FRUIT"), KUMQUAT("KUMQUAT", "FRUIT"),
    NECTARINE("NECTARINE", "FRUIT"), LYCHEE("LYCHEE", "FRUIT"), MANGOSTEEN("MANGOSTEEN", "FRUIT"),
    CARROT("CARROT", "VEGETABLE"), ELEPHANT("ELEPHANT", "ANIMAL"), KANGAROO("KANGAROO", "ANIMAL"),
    CHEETAH("CHEETAH", "ANIMAL"), ALLIGATOR("ALLIGATOR", "ANIMAL"), GIRAFFE("GIRAFFE", "ANIMAL"),
    HAMSTER("HAMSTER", "ANIMAL"), DOLPHIN("DOLPHIN", "ANIMAL");

    public String name;
    public String category;

    Words(String name, String category) {
        this.name = name;
        this.category = category;
    }

}
